In [1]:
import warnings
warnings.simplefilter('ignore')

In [2]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np
import pandas as pd

#  import data visualization library

In [5]:
pip install matplotlib

Note: you may need to restart the kernel to use updated packages.


In [6]:
pip install seaborn

Note: you may need to restart the kernel to use updated packages.


In [7]:
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

# importing dataset

In [8]:
pip install openpyxl

Note: you may need to restart the kernel to use updated packages.


In [9]:
ds=pd.read_excel('student_dataset.xlsx')

In [10]:
ds

S.NO  ATTN  THEORY  Daily assn  TOTAL    certificate
0       1    20      38          25     83    DISTINCTION
1       2    15      25           0     40     COMPLETION
2       3    20      31          25     76    FIRST CLASS
3       4    20      25          25     70    FIRST CLASS
4       5    20      17          15     52    FIRST CLASS
..    ...   ...     ...         ...    ...            ...
362   363    15       0          10     25  PARTICIPATION
363   364    20       9          25     54     COMPLETION
364   365    15      20          25     60    FIRST CLASS
365   366    15       0          10     25  PARTICIPATION
366   367    20      23          10     53     COMPLETION

[367 rows x 6 columns]

In [11]:
ds.shape

(367, 6)

In [12]:
ds.head()

S.NO  ATTN  THEORY  Daily assn  TOTAL  certificate
0     1    20      38          25     83  DISTINCTION
1     2    15      25           0     40   COMPLETION
2     3    20      31          25     76  FIRST CLASS
3     4    20      25          25     70  FIRST CLASS
4     5    20      17          15     52  FIRST CLASS

In [13]:
ds.tail()

S.NO  ATTN  THEORY  Daily assn  TOTAL    certificate
362   363    15       0          10     25  PARTICIPATION
363   364    20       9          25     54     COMPLETION
364   365    15      20          25     60    FIRST CLASS
365   366    15       0          10     25  PARTICIPATION
366   367    20      23          10     53     COMPLETION

# slice the dataset

In [14]:
data=ds.drop(['S.NO','TOTAL'],axis=1)

In [15]:
data

ATTN  THEORY  Daily assn    certificate
0      20      38          25    DISTINCTION
1      15      25           0     COMPLETION
2      20      31          25    FIRST CLASS
3      20      25          25    FIRST CLASS
4      20      17          15    FIRST CLASS
..    ...     ...         ...            ...
362    15       0          10  PARTICIPATION
363    20       9          25     COMPLETION
364    15      20          25    FIRST CLASS
365    15       0          10  PARTICIPATION
366    20      23          10     COMPLETION

[367 rows x 4 columns]


# unique value in dataset 

In [16]:
data['ATTN'].unique()

array([20, 15,  1, 25, 10], dtype=int64)

# grouping the dataset 

In [17]:
data.groupby('certificate').size()

certificate
COMPLETION       117
DISTINCTION       32
FIRST CLASS       66
PARTICIPATION    152
dtype: int64

# encoding the data

In [18]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [19]:
from sklearn.preprocessing import LabelEncoder

# implementing label encoder 

In [20]:
data.iloc[:,3]=LabelEncoder().fit_transform(data.iloc[:,3])

In [21]:
data

ATTN  THEORY  Daily assn  certificate
0      20      38          25            1
1      15      25           0            0
2      20      31          25            2
3      20      25          25            2
4      20      17          15            2
..    ...     ...         ...          ...
362    15       0          10            3
363    20       9          25            0
364    15      20          25            2
365    15       0          10            3
366    20      23          10            0

[367 rows x 4 columns]


## 0-compltion
## 1-distinction
## 2-first class
## 3-participation

#  reshape dataset to dataframe


In [22]:
x=data.iloc[:,:-1].values

In [23]:
x

array([[20, 38, 25],
       [15, 25,  0],
       [20, 31, 25],
       ...,
       [15, 20, 25],
       [15,  0, 10],
       [20, 23, 10]], dtype=int64)

In [24]:
y=data.iloc[:,3]

In [25]:
y

0      1
1      0
2      2
3      2
4      2
      ..
362    3
363    0
364    2
365    3
366    0
Name: certificate, Length: 367, dtype: int32

# converting to dataframe

In [26]:
x_frame=pd.DataFrame(x)

In [27]:
x_frame

0   1   2
0    20  38  25
1    15  25   0
2    20  31  25
3    20  25  25
4    20  17  15
..   ..  ..  ..
362  15   0  10
363  20   9  25
364  15  20  25
365  15   0  10
366  20  23  10

[367 rows x 3 columns]

In [28]:
y_frame=pd.DataFrame(y)

In [29]:
y_frame

certificate
0              1
1              0
2              2
3              2
4              2
..           ...
362            3
363            0
364            2
365            3
366            0

[367 rows x 1 columns]

# 4.divide the dataset into training set 

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
x_train,x_test,y_train,y_test=train_test_split(x_frame,y_frame,test_size=0.2,random_state=0)

# KNN 

In [32]:
from sklearn.neighbors import KNeighborsClassifier

In [33]:
knn=KNeighborsClassifier(n_neighbors=5)

In [34]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

# 6.prediction

In [35]:
y_predict=knn.predict(x_test)

In [36]:
y_predict

array([3, 2, 0, 3, 3, 3, 3, 3, 0, 0, 3, 0, 0, 2, 0, 1, 0, 2, 1, 3, 3, 0,
       1, 0, 3, 3, 3, 0, 0, 2, 3, 2, 3, 3, 0, 0, 2, 3, 3, 0, 0, 3, 0, 3,
       0, 0, 0, 0, 3, 3, 3, 2, 0, 1, 3, 0, 0, 3, 2, 0, 2, 0, 1, 0, 3, 0,
       0, 3, 0, 3, 0, 3, 3, 0])




# model evaluation amd performance metrics

In [37]:
knn.score(x_train,y_train)

0.7849829351535836

In [38]:
knn.score(x_test,y_test)

0.6891891891891891

# importing necessary metric

In [39]:
from sklearn.metrics import confusion_matrix

#  confusion matrix

In [40]:
 con_matrix=confusion_matrix(y_test,y_predict)

In [41]:
con_matrix

array([[15,  0,  2,  1],
       [ 0,  3,  2,  0],
       [ 7,  2,  5,  0],
       [ 9,  0,  0, 28]], dtype=int64)

# 