# NUMPY

In [1]:
pip install numpy

# numpy array operatios
1.importing library

In [2]:
import numpy as np


## 2.numpy version check
we perform this operation to know/check the version of installed numpy library

In [3]:
np.version.version

'1.25.2'

# 3. one dimensional array
we will be using numpy.array to create different dimansional
# 3.1 creating 1d array
 ### 1.syntax:numpy.array([values])
 ### 2.values:elements in the array

In [4]:
first_array=np.array([1,2,3,4,5,6,7,8,9])

In [5]:
print(first_array)

[1 2 3 4 5 6 7 8 9]


# 4 .two  dimensionl array
## 4.1 creating 2d array
### 1.syntax:numpy.array([(1,2,3),(4,5,6)])
### 2.values:elements in the array

In [6]:
second_array=np.array([(1,2,3),(5,6,7)])

In [7]:
print(second_array)

[[1 2 3]
 [5 6 7]]


#  5.three dimensional array
## 5.1 creating 3d array
### 1.syntax:numpy.array([(1,2),(3,4),(5,6)])
### 2.values:elements in the array

# 6.
## 1.syntax: numpy.zeros(shape,dtype=float,order="c")
## 2.shape of the array
## 3.dtype(optional):desired dtype of array
## 4.order:to store multi diemensional


In [8]:
z_array=np.zeros((3,2))

In [9]:
print(z_array)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


# 7.array of ones
## to create array containing only elements 1
### 1.syntax:numpy.ones()

In [10]:
o_array=np.ones((2,2))

In [11]:
print(o_array)

[[1. 1.]
 [1. 1.]]


# 8.linspace
### 1.syntax:numpy.linsapce(start,stop,num=50,endpoint=true,dtype=none,axis=0)
### 2.star:starting value of sequence
### 3.stop:end value off sequence
### 4.num=:number os samples to generate
### 5.endpoint:in true stop at last sample,otherwise it is included.default is true
### 6.dtype(optional):desired dtype of array
### 7.axis(optional):axis along which it is stored

In [12]:
lin=np.linspace(0,10,50)

In [13]:
print(lin)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


# array manipulation
### creating arrays

In [14]:
a=np.array([(1,2,3),(5,6,7),(8,9,10)])

In [15]:
print(a)

[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]]


In [16]:
b=np.array([(5,6,7,8,8),(1,2,3,4,5)])

In [17]:
print(b)

[[5 6 7 8 8]
 [1 2 3 4 5]]


# TRANSPOSE
### 1.syntax:numpy.transpose(a,axes=nonr)
### 2.a=:input array
### 3.axes:by default reverse the dimensions,permutes the matrix with respect to the provided value
### 4.output:n dimensional array whose dimensions are permuted

In [18]:
tran=np.transpose(a)

In [19]:
print(tran)

[[ 1  5  8]
 [ 2  6  9]
 [ 3  7 10]]


# flattening array
### 1.syntax:ndarray.ravel(order='c')
### 2.order:which orders the flattening

In [20]:
tran.ravel()

array([ 1,  5,  8,  2,  6,  9,  3,  7, 10])

# 11.reshaping an array
### 1.syntax:ndarray.reshape(newshape)
### 2,newshape:which shape is the out put is needed
#### imp:new shape should be compatibles ith old shape

In [21]:
b.reshape(5,2)

array([[5, 6],
       [7, 8],
       [8, 1],
       [2, 3],
       [4, 5]])

# 12. array resize
## we use ndarray.resize for resizing operation
### 1.syntax:ndaray.resize((new_size))
### 2.new_size:shape of resize for output

In [22]:
first=np.array([1,2,3,4,5,6,7,8,9])

In [23]:
b

array([[5, 6, 7, 8, 8],
       [1, 2, 3, 4, 5]])

In [25]:
b.resize((b))

TypeError: only integer scalar arrays can be converted to a scalar index

In [26]:
b

array([[5, 6, 7, 8, 8],
       [1, 2, 3, 4, 5]])

# 